### ISSUE TITLE
为什么 font-size = 4px  好难受/

### ISSUE THREAD

**Issue by Hillsir** [zhoukaiyue/vue3-pc-tmp#1]

**Comment by zhoukaiyue** [comment]
UnoCSS 中使用的单位关系是 1px = 0.25rem 相当于 1rem = 4px，这样当使用 UnoCSS 的预设属性时，可以通过属性名直接了解对应的尺寸或间距值。
例如，当使用 `.mt-10` 这个类名时，根据单位关系，可以推断出这个类名表示该元素的上边距为 10 像素（10px = 10 * 0.25rem）。这样可以提高代码的可读性和理解性，让开发人员更直观地了解样式的含义。
